version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # We only use dependabot for security updates since this is a library. See
    # https://github.com/freelawproject/eyecite/issues/42 for more discussion.
    open-pull-requests-limit: 1
    ignore:
    - dependency-name: "*"
