name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FREELAWBOT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run linters
        run: |
          ruff check .
          black --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FREELAWBOT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q --cov=.

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FREELAWBOT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-benchmark

      - name: Run benchmarks
        run: pytest --benchmark-only --benchmark-json=benchmark.json

      - name: Convert benchmark results
        run: |
          python - <<'EOF'
          import json
          with open("benchmark.json") as f:
              data = json.load(f)
          with open("benchmark-results.txt", "w") as f:
              for bench in data["benchmarks"]:
                  f.write(f"{bench['fullname']}: {bench['stats']['mean']:.6f} sec\n")
          EOF

      - name: Benchmark Pull Request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: benchmark
          GITHUB_TOKEN: ${{ secrets.FREELAWBOT_TOKEN }}
          path: benchmark-results.txt

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FREELAWBOT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
